PREFIX od:    <http://data.odeuropa.org/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>
PREFIX reo:   <https://read-it.acc.hum.uu.nl/ontology#>

# What types of cooking produce a bad smell?

SELECT ?cookingType
WHERE {
  ?assignment a crm:E13_Attribute_Assignment;
          crm:P2_has_type "hedonic" ;
          crm:P141_assigned "disgusting" ;
          crm:P140_assigned_attribute_to ?smell .

  ?emission od:F4_had_source / crm:P137_exemplifies ?source ;
            od:P1_generated ?smell .

  ?production crm:P108_has_produced ?source ;
    crm:P33_used_specific_technique ?cookingType .

  ?cookingType crm:P2_has_type "cooking"
}
